### ISSUE TITLE
A scroll bar appears at table of contents

### ISSUE THREAD

**Issue by fu-sen** [qqhann/hugo-primer#15]
When I refer to this theme, I see the scroll bar in the table of contents:
このテーマを参照した時、目次にスクロールバーを見ます。
![](https://user-images.githubusercontent.com/5434159/50557617-42ae0880-0d2a-11e9-9ea1-a4f8d8ed608c.jpg)

This scroll bar is not displayed in IE, but it is displayed in Chrome, Firefox and Edge.
このスクロールバーは IE では表示されませんが、Chrome・Firefox・Edge では表示されています。
This has destroyed the design of the theme.
これにより、テーマのデザインを崩してしまっています。

This solution is a simple CSS addition:
この解決はシンプルなCSSの追加です。

**static/assets/style.css**
```
.pr-3 {
  overflow: auto;
}
```

**Comment by qqhann** [comment]
あ，Edgeと書いてあるからWindowsでしたね，すみません．
近日中に修正対応します！

I just noticed you wrote Edge, so you are on Windows, right?
I'll work on this in a few days!

**Comment by fu-sen** [comment]
Thank you for commenting from the New Year. 😄
新年からのコメント、ありがとうございます。

I also use Chromium OS (CloudReady), and Android...
自分は Chromium OS (Cloudready) も使ってます。あとは Android……

I found another place to fix, so I will issue another one.
他に修正すべきところを見つけました。もう一つ issue しておきます。
