### ISSUE TITLE
The name shown in copyright.html should be the author of the website.

### ISSUE THREAD

**Issue by KosukeKamiya** [qqhann/hugo-primer#22]
Now, what shown in copyright.html is the author of the theme. However, I think it should be the author of the website that uses this theme.

If it goes on like this, readers should misunderstand that "Qiushi Pan" is the author of contents published on the blog that is using this theme.

https://github.com/qqhann/hugo-primer/blob/0df6b6735b69ff808af1055fd540c0463acfa62a/layouts/partials/copyright.html#L1

How do you think about it?

**Comment by qqhann** [comment]
Thank you for bringing up the problem.

**Comment by qqhann** [comment]
@KosukeKamiya 
You can add your own copyright by configuring your `config.toml`
```
# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = ""
```

**Comment by KosukeKamiya** [comment]
Thank you~!
