### ISSUE TITLE
May I add support for ruby tag in HTML

### ISSUE THREAD

**Issue by keaising** [qqhann/hugo-primer#28]
Hi Pan,

I pretty like your theme hugo-primer, it's brief and beautiful.

And I commit a hugo shortcodes to my fork, and it add support for ruby tag in this theme.

You can find the definition of ruby tag in [MDN Web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby) and my commit in [add support for ruby tag in HTML ](https://github.com/keaising/hugo-primer/commit/3048cd68f8b56972aef7c4cbedeefae47fa23996).

The result of ruby tag in hugo-primer is like this:

![图片](https://user-images.githubusercontent.com/8179012/57944689-5ee1c900-790a-11e9-8ae2-86f209a76170.png)

And you just need one line shortcodes code:

```
{{< ruby rb="深表遗憾" rt="Xi Wen Le Jian" >}}

{{< ruby rb="My heart is broken." rt="I'm happy for that." >}}
```
There is an actual view of this shortcodes at the beginning of [this post](http://shuxiao.wang/posts/cli-app-in-csharp1/).

Would you like merge this shortcodes into your original repo?

I can make a pull request for that.

Thanks for reading.

**Comment by qqhann** [comment]
Hello Wang,

I'm glad you like the theme!
And thank you for opening the issue. Your idea of ruby looks great!

Please open a pull request! 😄 
And please add the usage guide or example to README.md, so that others will understand how to use it.

**Comment by keaising** [comment]
Thank you!

I open a [pull request](https://github.com/qqhann/hugo-primer/pull/29) for this issue.
