### ISSUE TITLE
add support for inline html tags

### ISSUE THREAD

**Issue by andreyorst** [qqhann/hugo-primer#40]
**Hugo version**: v0.68.1

I've noticed that these codes have no effect, and it seems that superscript is not supported at all...

**Comment by qqhann** [comment]
Hi,

What do you need this for? Is Mathjax not enough?
Could you provide an example markdown you are experiencing this problem?

**Comment by andreyorst** [comment]
I don't want to use full blown javascript based LaTeX equation renderer for creating superscript notes in the average text here and there <sup>because this is what `<sup>` tag is for</sup>. I also do not use mathjax, and don't want any js on my page.

example markdown:
```markdown
bla bla bla<sup>(bla bla)</sup>bla bla
```

As for `<code>` tag and all other HTML tags, some times it is the only way to make this kind of stuff:

```markdown
<code>int<i>eger</i><code>
```

which should render as: <code>int<i>eger</i></code>. This impossible to do with plain markdown, because it escapes shortcodes inside <code>`</code> and <code>```</code> blocks.

Support for HTML tags is crucial. Even in this comment I'm using a lot of em.

**Comment by andreyorst** [comment]
It also prevents me from inlining images with `<embed>` tag, which I've did with my previous theme to have interactive svgs on the page.

**Comment by andreyorst** [comment]
It also seems that I cant jump on the `<a>` tag from the link, and it is only possible to make references to headings, not to figures:

![image](https://user-images.githubusercontent.com/19470159/79688843-b34ba200-8259-11ea-901d-15d42d333ce5.png)

Because that `<a>` tag is ignored and absent in resulting html.

**Comment by andreyorst** [comment]
It seems I can enable all of these by adding this snippet to my config.toml:

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```
